In [1]:
import numpy as np

In [6]:
def symPositiveDef(n,p,m):
    Pd=np.zeros((n,p,m))
    for i in range(m):
        A=np.random.rand(n,p)
        Pd[:,:,i]=A@A.T+ n* np.eye(n)
    return Pd
    

In [19]:
def SqrtOfsymPositiveDef(A):
    m,n,p=A.shape
    Af=np.fft.fft(A,axis=2)
    V=np.zeros((m,n,p),dtype=complex)
    D=np.zeros((m,n,p),dtype=complex)
    Sf=np.zeros((m,n,p),dtype=complex)
    for i in range(p):
        Eval,EVec=np.linalg.eig(Af[:,:,i])
        V[:,:,i]=EVec
        D[:,:,i]=np.diag(Eval)
        Sf[:,:,i]=V[:,:,i] @ np.sqrt(D[:,:,i]) @ V[:,:,i].T
    S=np.fft.ifft(Sf,axis=2)
    return S.real
        

In [20]:
A=symPositiveDef(3,3,3)
A

array([[[3.46596077, 3.7011227 , 4.40547217],
        [0.43744193, 0.39779118, 0.53724394],
        [0.69705436, 0.37519772, 0.44440732]],

       [[0.43744193, 0.39779118, 0.53724394],
        [4.0168699 , 4.27070923, 3.67866832],
        [0.77667318, 0.90108945, 0.80501505]],

       [[0.69705436, 0.37519772, 0.44440732],
        [0.77667318, 0.90108945, 0.80501505],
        [4.07522266, 3.88901329, 4.01864801]]])

In [21]:
As=SqrtOfsymPositiveDef(A)

In [22]:
As

array([[[ 1.31655558,  0.5671458 ,  1.50619324],
        [ 0.08960287, -0.02046979,  0.12089308],
        [ 0.18619358,  0.07944907, -0.05336901]],

       [[ 0.08960287, -0.02046979,  0.12089308],
        [ 1.48839563,  1.25696537,  0.69030948],
        [ 0.07533982,  0.21335817,  0.06669736]],

       [[ 0.18619358,  0.07944907, -0.05336901],
        [ 0.07533982,  0.21335817,  0.06669736],
        [ 1.37348225,  0.92401516,  1.1392915 ]]])

In [23]:
def tProduct(A,B,o):
    AFFT=np.fft.fft(A,axis=o-1)
    BFFT=np.fft.fft(B,axis=o-1)
    CFFT=np.zeros((A.shape[0],B.shape[1],o),dtype=complex)
    for i in range(o):
        CFFT[:,:,i]=np.dot(AFFT[:,:,i],BFFT[:,:,i])
    C=np.fft.ifft(CFFT)
    return C.real
    

In [24]:
tProduct(As,As,3)

array([[[3.47104813, 3.80535693, 4.29615057],
        [0.43483229, 0.41372287, 0.5239219 ],
        [0.66264621, 0.37581726, 0.47819592]],

       [[0.43483229, 0.41372287, 0.5239219 ],
        [3.98792808, 4.26579481, 3.71252457],
        [0.77882011, 0.89380485, 0.81015272]],

       [[0.66264621, 0.37581726, 0.47819592],
        [0.77882011, 0.89380485, 0.81015272],
        [4.05222348, 3.9052533 , 4.02540718]]])