In [1]:
import numpy as np


In [5]:
A=np.random.rand(3,3,3)
A

array([[[0.10296407, 0.46013405, 0.25206218],
        [0.86258096, 0.22784617, 0.68295051],
        [0.50813609, 0.66649912, 0.28626777]],

       [[0.47554103, 0.2419302 , 0.68581627],
        [0.8305085 , 0.33443162, 0.2650076 ],
        [0.071837  , 0.21757278, 0.83797268]],

       [[0.56296579, 0.58518562, 0.47940734],
        [0.6586859 , 0.83576602, 0.31556957],
        [0.42514433, 0.11432446, 0.3018554 ]]])

In [6]:
V=np.zeros((3,1,3))
D=np.zeros((3,3,3))
Af=np.fft.fft(A,axis=2)
    

In [56]:

for i in range(1):
    V1,D1=np.linalg.eig(Af[:,:,i])

In [61]:
V1

array([3.5358201 -1.11022302e-16j, 0.30530596+4.14317100e-01j,
       0.30530596-4.14317100e-01j])

In [62]:
D1

array([[ 0.52277275-8.32667268e-17j, -0.50091224+2.84716348e-01j,
        -0.50091224-2.84716348e-01j],
       [ 0.64744346+0.00000000e+00j, -0.23407734-3.25950772e-01j,
        -0.23407734+3.25950772e-01j],
       [ 0.55454992-2.77555756e-17j,  0.71203049+0.00000000e+00j,
         0.71203049+0.00000000e+00j]])

In [25]:
V=np.zeros((3,3,3),dtype=complex)
D=np.zeros((3,3,3),dtype=complex)


In [49]:

for i in range(3):
    D1,V1=np.linalg.eig(Af[:,:,i])
    V[:,:,i]=V1
    D[:,:,i]=np.diag(D1)
    
    

In [50]:
V[:,:,0]

array([[ 0.57234201-0.j,  0.79091486+0.j, -0.41253281+0.j],
       [ 0.55874458-0.j, -0.21531273+0.j,  0.7157665 +0.j],
       [ 0.6001909 +0.j, -0.572795  +0.j, -0.56346695+0.j]])

In [51]:
D[:,:,0]

array([[ 4.07839415+0.j,  0.        +0.j,  0.        +0.j],
       [ 0.        +0.j, -0.72562338+0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j, -0.26633857+0.j]])

In [52]:
V1

array([[ 0.20195117-0.17396869j,  0.85176979+0.j        ,
         0.79700764+0.j        ],
       [ 0.78088214+0.j        , -0.30238132+0.37912164j,
         0.14403096-0.16012557j],
       [-0.03012793+0.5641507j ,  0.08895175+0.17722336j,
        -0.29498778-0.48101551j]])

In [53]:
S=np.zeros((3,3,3))
for i in range(3):
    S[:,:,i]=np.dot(V[:,:,i],np.sqrt(D[:,:,i]),np.linalg.inv(V[:,:,i]))

C:\Users\cks12\AppData\Local\Temp\ipykernel_6316\3817705093.py:3: ComplexWarning: Casting complex values to real discards the imaginary part
  S[:,:,i]=np.dot(V[:,:,i],np.sqrt(D[:,:,i]),np.linalg.inv(V[:,:,i]))


In [58]:
Sf=np.fft.ifft(S,axis=2)
Sf.real

array([[[ 0.49062174,  0.33261246,  0.33261246],
        [ 0.22938455, -0.11469228, -0.11469228],
        [ 0.09418686, -0.04709343, -0.04709343]],

       [[ 0.86683509,  0.13077576,  0.13077576],
        [-0.25110031,  0.12555016,  0.12555016],
        [-0.01726801,  0.008634  ,  0.008634  ]],

       [[ 0.45503348,  0.37852706,  0.37852706],
        [-0.0553576 ,  0.0276788 ,  0.0276788 ],
        [-0.13786401,  0.068932  ,  0.068932  ]]])

In [63]:
A=np.random.rand(3,3)

In [64]:
A

array([[0.98261275, 0.69716208, 0.74862663],
       [0.47276707, 0.58033808, 0.93661475],
       [0.39608769, 0.8977583 , 0.23451248]])

In [65]:
A.T

array([[0.98261275, 0.47276707, 0.39608769],
       [0.69716208, 0.58033808, 0.8977583 ],
       [0.74862663, 0.93661475, 0.23451248]])

In [66]:
A@A.T

array([[2.01200462, 1.57031141, 1.19064616],
       [1.57031141, 1.43754819, 0.9279084 ],
       [1.19064616, 0.9279084 , 1.01785154]])

In [68]:
def symPositiveDef(n,p,m):
    Pd=np.zeros((n,p,m))
    for i in range(m):
        A=np.random.rand(n,p)
        Pd[:,:,i]=A@A.T+ n* np.eye(n)
    return Pd
    

In [70]:
A=symPositiveDef(3,3,3)

In [72]:
def SqrtOfsymPositiveDef(A):
    m,n,p=A.shape
    Af=np.fft.fft(A,axis=2)
    V=np.zeros((m,n,p),dtype=complex)
    D=np.zeros((m,n,p),dtype=complex)
    Sf=np.zeros((m,n,p),dtype=complex)
    for i in range(p):
        Eval,EVec=np.linalg.eig(Af[:,:,i])
        V[:,:,i]=EVec
        D[:,:,i]=np.diag(Eval)
        Sf[:,:,i]=np.dot(V[:,:,i],np.sqrt(D[:,:,i]),np.linalg.inv(V[:,:,i]))
    S=np.fft.ifft(Sf,axis=2)
    return S.real
        

In [73]:
SqrtOfsymPositiveDef(A)

array([[[ 1.07178466,  0.36874303,  1.10455895],
        [ 1.02092651,  0.88486372,  0.51517585],
        [ 0.14974651,  0.01973317,  0.09014807]],

       [[ 1.33454307, -0.08840036,  1.31785936],
        [-0.44826684, -0.61527451, -0.40287932],
        [-0.69927981, -0.62022798, -0.55769989]],

       [[ 0.97592586, -0.14644033,  0.88787517],
        [-0.66665969, -0.33322318, -0.39857864],
        [ 0.86601353,  0.83905711,  0.71281937]]])